# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      

# Specifies where the analysis results should be sent.

  # Coverity Connect configuration to use when committing defects to Coverity
  # Connect.
  connect:

  #### need to add variables for credentials
 
    # The name of the stream to commit the results to.
    stream: sls-bodgeit-master

    # Absolute URL of where to commit the Coverity Connect results.
    # url: https://testing.coverity.synopsys.com:443
    url: https://poc391.coverity.synopsys.com 
     



